# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('TP1', 'USERLOG'), ('TP2', 'PAYLOG')], max_length=4)),
                ('log_path', models.CharField(max_length=20)),
                ('timing', models.IntegerField()),
            ],
        ),
    ]
